### ISSUE TITLE
Run-time error '13': Type mismatch

### ISSUE THREAD

**Issue by vort3** [mirinsoft/CloneApp#3]
I can't make it work, see this error message every time I press the Get List button. Is there a fix?

**Comment by Belim** [comment]
Which "Get list" button do you exactly mean? Can you please upload an screenshot, thanks.

**Comment by vort3** [comment]
I'm talking about Add-on S.exe file, here's the screenshot:
https://i.imgur.com/HyeZiCw.png

**Comment by Belim** [comment]
Add-on S was not compatible with latest v2.14.555 of CloneApp.  Due to my server migration also the plugins folder was moved and not accessible https://www.mirinsoft.com/blog/12-company-announcements/14-it-s-here-announcing-the-launch-of-new-mirinsoft-website

I have updated all plug-ins and provided an updated version of Add-on S
https://github.com/mirinsoft/CloneApp/blob/master/addons/add-on-s.zip

In the future I will no longer support and develop this little helper
All external plug-ins can also be downloaded here manually
https://github.com/mirinsoft/CloneApp/tree/master/plugins

**Comment by vort3** [comment]
So, no more app plugins other than preinstalled? The link you provided only contains plugins for browser passwords, saved networks etc., but no plugins for other apps (a lot apps I use don't have a plugin, unfortunately).

**Comment by Belim** [comment]
Of course new Plug-ins will be added an supported. 
I will ONLY discontinue the development of Add-ons S. In this sense these are not real CloneApp plug-ins but only third party files from NirSoft utilities, e.g. ProduKey. They can also be downloaded and integrated at any time without Add-on S.
